### PR TITLE
Include Port Generation Logic in V1 Docker Creator

### PR DESCRIPTION
**Pull request by bm1549**
Makes the port generation logic introduced in https://github.com/paradoxical-io/docker-client/pull/4 available in the V1 Docker Creator

### CODE REVIEW

**Review by devshorts — APPROVED** [review]

**Comment by devshorts** [comment]
Good change @bm1549, tell christian he's a dumbass

**Comment by devshorts** [comment]
Released in 1.27

**Comment by bm1549** [comment]
image

public List<CSVRecord> getRecords()

**Pull request merged**
